apiVersion: v1
kind: Service
metadata:
  name: voicevox
spec:
  ports:
  - protocol: TCP
    port: 50021
    targetPort: 50021
  selector:
    app: voicevox
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.122.124
